spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team10?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: qq85689049
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10            #连接池的配置信息,初始化大小，最小，最大
    min-idle: 5
    initial-size: 5
    max-wait: 10000           #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000     #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM student
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    database: MYSQL
    show-sql: true   #打印SQL语句
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        enable_lazy_load_no_trans: true

